name: flutter_praia_limpa
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  #sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.4.2
  rect_getter: ^0.0.1
  gradient_text: ^1.0.2
  #cloud_firestore: ^0.9.13+1
  shared_preferences: ^0.5.2
  flutter_spinkit: ^3.1.0
  sensors: ^0.4.0+1
  camera: ^0.5.2+1
  google_maps_flutter: ^0.5.21
  path_provider: ^1.1.0
  image_picker: ^0.6.0+10
  qr_flutter: ^2.0.0
  geolocator: ^5.0.1
  badges: ^1.0.3
  font_awesome_flutter: ^8.4.0
  file_picker: ^1.3.7
  sticky_header_list: ^1.0.6
  url_launcher: ^5.0.5
  fluttertoast: ^3.1.0
  custom_radio_button: ^0.0.3
  sliding_up_panel: ^0.3.4
  grouped_buttons: ^1.0.4
  flare_flutter: ^1.5.4
  flutter_staggered_grid_view: ^0.3.0
  flutter_facebook_login: ^2.0.1
  http: ^0.12.0+2
  flutter_cache_manager: ^1.1.1
  expandable: ^3.0.0+1
  image: ^2.1.4
  liquid_pull_to_refresh: ^1.1.1
  dio: ^2.1.13
  flutter_image_compress: ^0.6.3
  permission_handler: ^3.0.0
  app_settings: ^1.0.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/logo.png
    - assets/login.jpg
    - assets/linha.png
    - assets/logo_b.png
    - assets/passo1.png
    - assets/passo2.png
    - assets/passo3.png
    - assets/bennefits.png
    - assets/001-fish.png
    - assets/002-shrimp.png
    - assets/003-kraken.png
    - assets/004-fish-1.png
    - assets/005-sea.png
    - assets/006-ocean.png
    - assets/trashIcons.png
    - assets/camera.png
    - assets/back-arrow.png
    - assets/pontos.png
    - assets/registros.png
    - assets/lista.png
    - assets/compartilhar.png
    - assets/clean_ac.png
    - assets/user.png
    - assets/clean_in.png
    - assets/inst.jpg
    - assets/pins/vermelho.png
    - assets/pins/verde.png
    - assets/pins/amarelo.png
    - assets/pins/azul.png
    - assets/pins/cinza.png
    - assets/pins/marrom.png
    - assets/pins/laranja.png
    - assets/pins/roxo.png
    - assets/waveMenu2.flr
    - assets/bottomMenu/mapa_.png
    - assets/bottomMenu/perfil_.png
    - assets/bottomMenu/registros_.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf    
    
    - family: Montserrat-Black
      fonts:
        - asset: assets/Montserrat-Black.ttf
   
    - family: Montserrat-Medium
      fonts:
        - asset: assets/Montserrat-Medium.ttf

    - family: NunitoBold
      fonts:
        - asset: assets/nubold.ttf

    - family: NunitoItalic
      fonts:
        - asset: assets/nuitalic.ttf

    - family: NunitoLight
      fonts:
        - asset: assets/nulight.ttf

    - family: NunitoRegular
      fonts:
        - asset: assets/nuregular.ttf
  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
